import { Header, DisableZoomWrapper } from "@/components";
import "./globals.css";
import { ReduxProvider } from "@/lib/provider/StoreProvider";
import { MessageProvider } from "@/lib/provider/MessageProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body>
        <DisableZoomWrapper>
        <Header />
        <ReduxProvider>
          <MessageProvider>{children}</MessageProvider>
        </ReduxProvider>
        </DisableZoomWrapper>
      </body>
    </html>
  );
}
