import { Header } from "@/components";
import "./globals.css";
import { ReduxProvider } from "@/lib/redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ReduxProvider>
            {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
