import { Header } from "@/components";
import "./globals.css";
import { ReduxProvider } from "@/lib/provider/StoreProvider";
import { MessageProvider } from "@/lib/provider/MessageProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ReduxProvider>
          <MessageProvider>{children}</MessageProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
